### PR TITLE
Add php 8 compatibility

### PR DESCRIPTION
**Pull request by daniloargentiero**

### CODE REVIEW

**Review by naseemqota — APPROVED** [review]

**Comment by daniloargentiero** [comment]
Thank you for merging my pull request. Please can you create a new release 1.0.1 ? Thanks

**Comment by naseemqota** [comment]
@daniloargentiero done.

**Comment by daniloargentiero** [comment]
Please can you update the packagist too?
https://packagist.org/packages/qota/customer-order-search

Thanks

**Comment by naseemqota** [comment]
@daniloargentiero  - please check now

**Comment by naseemqota** [comment]
@daniloargentiero -  please check some bugs are fixed and code is refactored. 
version - 1.0.2 released.

**Pull request merged**
